# Generated by Django 4.1.4 on 2022-12-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUploaded', models.TimeField(auto_created=True)),
                ('offerName', models.CharField(max_length=255)),
                ('offerImage', models.ImageField(upload_to='images/Offers/')),
            ],
        ),
    ]
