# Generated by Django 4.1.4 on 2022-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_offerslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerslider',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
