# Generated by Django 4.1.4 on 2022-12-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offerslider_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeBlockOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUploaded', models.TimeField(auto_created=True)),
                ('offerName', models.CharField(max_length=255)),
                ('offerImage', models.ImageField(upload_to='images/Offers/')),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
