# Generated by Django 4.1.4 on 2022-12-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_homeblockoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeblockoffers',
            name='dateUploaded',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
