# Generated by Django 4.1.4 on 2022-12-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_collection_products_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='collection',
        ),
        migrations.AddField(
            model_name='collection',
            name='collectionImage',
            field=models.ImageField(null=True, upload_to='images/collection/'),
        ),
        migrations.AddField(
            model_name='homeblockoffers',
            name='linkToOffer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
