# Generated by Django 4.1.4 on 2023-01-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_products_collection_alter_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='care',
            field=models.CharField(default='Machine Wash', max_length=255),
        ),
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(default='100% Cotton', max_length=255),
        ),
    ]
