# Generated by Django 4.1.4 on 2023-01-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_products_care_products_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='miscImage1',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='miscImage2',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/products/'),
        ),
        migrations.AddField(
            model_name='products',
            name='miscImage3',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/products/'),
        ),
    ]
