# Generated by Django 4.1.4 on 2023-01-08 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_offers'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_in_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='offerBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='offerName',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offerPrice',
            field=models.CharField(default='100', max_length=255, null=True),
        ),
    ]
